# Add GStreamer dev headers and plugins to the complete ARM64 Qt build image
# These are required to build OpenterfaceQT which depends on GStreamer backend
ARG BASE_IMAGE=docker.io/library/openterface-qtbuild-complete:arm64
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        libbz2-dev \
        libgudev-1.0-dev \
        libv4l-dev \
        libxcb-cursor-dev \
        liborc-0.4-dev \
        libxi-dev \
        libxv-dev \
        libgstreamer1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-bad \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
