---
name: Linux build from Source

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build script
        run: |
          chmod +x docker/build-from-source.sh
          ./docker/build-from-source.sh 