---
name: Linux build from Source

on: 
  workflow_dispatch:

env:
  SOURCE_DIR: ${{ github.workspace }}
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
            path: ${{ env.SOURCE_DIR }}/qt-build/
            key: dependencies-cache
            restore-keys: |
              dependencies-cache

      - name: Run build script
        run: |
          chmod +x build-script/build-from-source.sh
          ./build-script/build-from-source.sh 