name: Test arm64 build

on:
  push:
    branches: ["main", "dev"]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-24.04-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          uname -m
          gcc -v  # Or your build commands